version: '3.9'

services:
  mongoapp:
    image: "almeidakaue/mongo-todo-db:latest"  
    restart: always                        
    environment:
      - MONGO_INITDB_DATABASE=admin      
      - MONGO_INITDB_ROOT_USERNAME=kako
      - MONGO_INITDB_ROOT_PASSWORD=1234
    volumes:
      - my-app:/data/db  
    ports:
      - 27017:27017
  app:
    build: .
    restart: always
    ports:
      - "3000:3000"
volumes:
  my-app:
    